#!/bin/bash
# This theme is for the Custom Drow script.  

# How to use:
# Change the names in the lines below to match the names of the theme
# style you want to use.

# Change gtktheme
xfconf-query -c xsettings -p /Net/ThemeName -s "Custom-drow"

## Change icon theme
xfconf-query -c xsettings -p /Net/IconThemeName -s "Obsidian"

## Change openbox theme
#sed -i "s/$(grep "<theme>" ~/.config/openbox/rc.xml -A 5 | grep "<name>"| awk -F"[><]" '{print $3}')/"Custom-drowbox"/g" ~/.config/openbox/rc.xml
xmlstarlet ed -L -N o="http://openbox.org/3.4/rc" -u '/o:openbox_config/o:theme/o:name' -v "Custom-drowbox" ~/.config/openbox/rc.xml
openbox --reconfigure

## Change Geany theme
sed -i "s/color_scheme=.*/color_scheme=Lilidog-Drow.conf/g" ~/.config/geany/geany.conf

## Change jgmenu theme
if test -e ~/.config/jgmenu/backup; then
rm -fr ~/.config/jgmenu/backup
fi
#jgmenu_run gtktheme
jgmenu_run init --apply-obtheme

## Change xfce4-terminal theme
xfce4-term-colors lilidog-drow

## Change Rofi theme
sed -i 's/^@theme "familiar.*/@theme "familiar-drow.rasi"/g' "$HOME/.config/rofi/themes/familiar/config.rasi"
sed -i 's/^@theme "rounded.*/@theme "rounded-drow.rasi"/g' "$HOME/.config/rofi/config.rasi"

# These lines are for the light/dark toggle and the custom toggle. Do not remove.
# Comment these lines in Custom-Theme or Light-Dark-Theme if copying a named theme.
rm -f ~/.cache/temp_theme
rm -f ~/.cache/custom_theme
