#!/bin/bash
# This theme is for the Light/Dark toggle script.  No additions should
# be made to this file other than changing the name in the existing
# lines. Any Other additions need to be added to the named scripts.

# How to use:
# Change the names in the lines below to match the names of the theme
# style you want to use.  Carefull about capitalization.  You can also 
# just copy and paste the relevant part of any of the named scripts in
# ~/.config/lilidog-themes

## Change gtktheme
xfconf-query -c xsettings -p /Net/ThemeName -s "Ghost"

## Change icon theme
xfconf-query -c xsettings -p /Net/IconThemeName -s "Obsidian-SemiLight"

## gsettings "gtk-theme" and "icons" for use is scripts like neofetch which won't use xfconf-query.
gsettings set org.gnome.desktop.interface gtk-theme "Ghost"
gsettings set org.gnome.desktop.interface icon-theme "Obsidian-Semilight"

## Change openbox theme
#sed -i "s/$(grep "<theme>" ~/.config/openbox/rc.xml -A 5 | grep "<name>"| awk -F"[><]" '{print $3}')/"Ghostbox"/g" ~/.config/openbox/rc.xml
xmlstarlet ed -L -N o="http://openbox.org/3.4/rc" -u '/o:openbox_config/o:theme/o:name' -v "Ghostbox" ~/.config/openbox/rc.xml
openbox --reconfigure

## Change Geany theme
sed -i "s/color_scheme=.*/color_scheme=Ghost.conf/g" ~/.config/geany/geany.conf

## Change jgmenu theme
#jgmenu_run gtktheme
if test -e ~/.config/jgmenu/backup; then
rm -fr ~/.config/jgmenu/backup
fi
jgmenu_run init --apply-obtheme >/dev/null 2>&1

## Change xfce4-terminal theme
xfce4-term-colors ghost

## Change Rofi theme
sed -i 's/^@theme "familiar.*/@theme "familiar-ghost.rasi"/g' "$HOME/.config/rofi/themes/familiar/config.rasi" >/dev/null 2>&1
sed -i 's/^@theme "rounded.*/@theme "rounded-ghost.rasi"/g' "$HOME/.config/rofi/config.rasi" >/dev/null 2>&1

# These lines are for the light/dark toggle and the custom toggle. Do not remove.
# Comment these lines in Custom-Theme or Light-Dark-Theme if copying a named theme.
# rm ~/.cache/temp_theme
# rm ~/.cache/custom_theme
