#!/bin/bash
#### A theme changer to set the theme to your own custom configuration.
### Simply change the "Lilidog" entries below with your own selections.

## Change gtktheme
xfconf-query -c xsettings -p /Net/ThemeName -s "Ozark"

## Change icon theme
xfconf-query -c xsettings -p /Net/IconThemeName -s "Obsidian-Aqua"

## gsettings "gtk-theme" and "icons" for use is scripts like neofetch which won't use xfconf-query.
gsettings set org.gnome.desktop.interface gtk-theme "Ozark"
gsettings set org.gnome.desktop.interface icon-theme "Obsidian-Aqua"

## Change openbox theme
#sed -i "s/$(grep "<theme>" ~/.config/openbox/rc.xml -A 5 | grep "<name>"| awk -F"[><]" '{print $3}')/"Ozarkbox"/g" ~/.config/openbox/rc.xml
xmlstarlet ed -L -N o="http://openbox.org/3.4/rc" -u '/o:openbox_config/o:theme/o:name' -v "Ozarkbox" ~/.config/openbox/rc.xml
openbox --reconfigure

## Change Geany theme
sed -i "s/color_scheme=.*/color_scheme=Ozark.conf/g" ~/.config/geany/geany.conf

## Change jgmenu theme
# jgmenu_run gtktheme
if test -e ~/.config/jgmenu/backup; then
rm -fr ~/.config/jgmenu/backup
fi
jgmenu_run init --apply-obtheme >/dev/null 2>&1

## Change xfce4-terminal theme
xfce4-term-colors ozark

## Change Rofi theme
sed -i 's/^@theme "familiar.*/@theme "familiar-ozark.rasi"/g' "$HOME/.config/rofi/themes/familiar/config.rasi" >/dev/null 2>&1
sed -i 's/^@theme "rounded.*/@theme "rounded-ozark.rasi"/g' "$HOME/.config/rofi/config.rasi" >/dev/null 2>&1

# These lines are for the light/dark toggle and the custom toggle. Do not remove.
# Comment these lines in Custom-Theme or Light-Dark-Theme if copying a named theme.
rm -f ~/.cache/temp_theme
rm -f ~/.cache/custom_theme
