#!/bin/bash
# Replace conky-chooser with lua addition for the dialog.
# Made by sleekmason 24.06.27
## Uncomment and use lua transparency
if grep -q '^--\?lua_load' "$HOME/.config/conky/conky-shortcuts.conf"; then
## Check for conky-choser-transparency script.
   if ! test -e "$HOME/.config/conky/scripts/conky-chooser-transparency"; then
   notify-send --urgency low "transparency chooser not found.. exiting."
   exit 0
   fi
cp "$HOME/.config/conky/scripts/conky-chooser" "$HOME/.config/conky/scripts/conky-chooser-notrans.bak"
cp -f "$HOME/.config/conky/scripts/conky-chooser-transparency" "$HOME/.config/conky/scripts/conky-chooser"
sed -i '/lua_load =/s/^--*//g' "$HOME"/.config/conky/*.conf 
sed -i '/lua_draw_hook_pre =/s/^--*//g' "$HOME"/.config/conky/*.conf
else
## Comment lua and use original default.
if test -e "$HOME/.config/conky/scripts/conky-chooser-notrans.bak"; then
cp -f "$HOME/.config/conky/scripts/conky-chooser-notrans.bak" "$HOME/.config/conky/scripts/conky-chooser"
sed -i '/lua_load =/s/^#*/--/g' "$HOME"/.config/conky/*.conf
sed -i '/lua_draw_hook_pre =/s/^#*/--/g' "$HOME"/.config/conky/*.conf
else
## If .bak file doesn't exist, copy back original from /etc/skell
cp -fr "/etc/skel/.config/conky" "$HOME/.config"
fi
fi
