#!/bin/bash

MAIN(){
if pgrep -x picom > /dev/null 2>&1; then
if pgrep -f "$FILE" > /dev/null; then
    pkill -f "$FILE"
    else   
    sed -i '/own_window_transparent/c\-- own_window_transparent = true,' "$FILE"
    sed -i '/own_window_argb_visual/c\own_window_argb_visual = true,' "$FILE"
    sed -i '/own_window_argb_value/c\own_window_argb_value = 0,' "$FILE"
    bash -c "conky -c $FILE"
    fi
else
if pgrep -f "$FILE" > /dev/null; then
    pkill -f "$FILE"
    else   
    sed -i '/own_window_transparent/c\own_window_transparent = true,' "$FILE"
    sed -i '/own_window_argb_visual/c\-- own_window_argb_visual = true,' "$FILE"
    sed -i '/own_window_argb_value/c\-- own_window_argb_value = 0,' "$FILE"
    bash -c "conky -c $FILE"
    fi
fi
}

RESTART(){
conkyfile=$HOME/.config/conky/scripts/conky-restart-list
# Copy currently running conkys to file -
ps aux | grep -i conky | awk '{ print $13 }' | tail > "$conkyfile" &&
# Adjust file for correct lines
sed -i "/^Conky\b/d" "$conkyfile"
sed -i "/^conky\b/d" "$conkyfile"
sed -i "/^KILLCONKY\b/d" "$conkyfile"
sed -i '/^[[:space:]]*$/d' "$conkyfile"
sed -i -e 's/^/conky -c /' "$conkyfile"
sed -i '1i #!/bin/bash' "$conkyfile"
chmod 755 "$conkyfile"
}

TIMEDATE(){
	FILE=$HOME/.config/conky/conky-clock-date.conf
$(MAIN) >/dev/null 2>&1 "$FILE"
}

FULLCONKY(){
FILE=$HOME/.config/conky/conky-full.conf
$(MAIN) >/dev/null 2>&1 "$FILE"
}

TAO(){
FILE=$HOME/.config/conky/conky-tao.conf
$(MAIN) >/dev/null 2>&1 "$FILE"
}

FORTUNES(){
FILE=$HOME/.config/conky/conky-fortunes.conf
$(MAIN) >/dev/null 2>&1 "$FILE"
}

SHORTCUTS(){
FILE=$HOME/.config/conky/conky-shortcuts.conf
$(MAIN) >/dev/null 2>&1 "$FILE"
}

BUILDDATE(){
FILE=$HOME/.config/conky/conky-build.conf
$(MAIN) >/dev/null 2>&1 "$FILE"
}

CURRENT(){
FILE=$HOME/.config/conky/conky-current.conf
$(MAIN) >/dev/null 2>&1 "$FILE"
}

WORLDCLOCK(){
FILE=$HOME/.config/conky/conky-world-clock.conf
$(MAIN) >/dev/null 2>&1 "$FILE"
}

KILLCONKY(){
killall "conky"
sleep .50
eval "$(RESTART)" >/dev/null 2>&1
}

export -f MAIN
export -f RESTART
export -f TIMEDATE
export -f FULLCONKY
export -f FORTUNES
export -f TAO
export -f SHORTCUTS
export -f BUILDDATE
export -f WORLDCLOCK
export -f KILLCONKY

if ! [[ $(command -v conky) ]]; then
notify-send --urgency low "Install 'conky-all' to use this dialog"
else
yad --title "Conky" --form --center --width=220 --height=600 \
--borders=12 --text="Toggle Your Selections\n" --text-align=center \
--window-icon=conky-logomark-violet \
    --form \
    --field="                          Clock!appointment-new":BTN "bash -c 'TIMEDATE' >/dev/null 2>&1 &" \
    --field="                     Full Info!dialog-information":BTN "bash -c 'FULLCONKY' >/dev/null 2>&1 &" \
    --field="                    Fortunes!emblem-package":BTN "bash -c 'FORTUNES' >/dev/null 2>&1 &" \
    --field="                   Shortcuts!accessories-text-editor":BTN "bash -c 'SHORTCUTS' >/dev/null 2>&1 &" \
    --field="              Tao Te Ching!application-x-addon":BTN "bash -c 'TAO' >/dev/null 2>&1 &" \
    --field="               World Clock!emblem-web":BTN "bash -c 'WORLDCLOCK' >/dev/null 2>&1 &" \
    --field="                Install Date!application-certificate":BTN "bash -c 'BUILDDATE' >/dev/null 2>&1 &" \
    --field="       12H/24H Format!appointment-new":FBTN "bash -c '~/.config/conky/scripts/conky-12to24'" \
    --field="       Bg Transparency!preferences-system":FBTN "bash -c '~/.config/conky/scripts/conky-bg-trans'" \
    --field="             Bg Tint Color!org.xfce.settings.color":FBTN "bash -c '~/.config/conky/scripts/conky-bg-color'" \
    --field="            Restart Conky!media-playlist-repeat":FBTN "conkyrestart" \
    --field="                  Kill Conky!process-stop":FBTN "bash -c KILLCONKY"
fi
eval "$(RESTART)" >/dev/null 2>&1
