#!/bin/bash
# Custom conky text color
# Made by sleekmason 07-31-2024
set -e
## "--color" can be removed if wanting to use a separate color chooser.
CHOICE=( $(yad --color --init-color=#c4c4c4 \
--gtk-palette --palette=/usr/share/X11/rgb.txt \
--form --width=320 --center --borders=6 --on-top \
--title="Custom Conky Text Color " \
--button=Cancel!gtk-delete:1 \
--button=Apply!gtk-color-picker:0 \
--window-icon=org.xfce.settings.color \
--text="Enter color choice:" --separator=' ' \
--field="Color"))

if (( $? == 1 )); then
    exit 0
else
# Continue Chosen Selection.
COLOR_CHOICE=${CHOICE}

##Remove "#" if present.
if [[ $COLOR_CHOICE == *#* ]]; then
    NEW_COLOR=$(echo $COLOR_CHOICE | sed 's|[#,]||g')
else
    NEW_COLOR=$COLOR_CHOICE
fi

## Grab the old color for variable use.
# OLD_COLOR=$(sed '/default_color/!d' "$HOME/.config/conky/conky-shortcuts.conf" | cut -d'#' -f2 | sed 's/..$//')
OLD_COLOR=$(sed '/default_color/!d' "$HOME/.config/conky/scripts/defaults.txt" | cut -d'#' -f2 | sed 's/..$//')

## Show numbers if in terminal.
echo "#$NEW_COLOR" >> "/tmp/custom_conky_color.txt"

## Make the change.
sed -i -e "s/${OLD_COLOR}/${NEW_COLOR}/g" "$HOME/.config/conky/scripts/defaults.txt"
sed -i -e "s/${OLD_COLOR}/${NEW_COLOR}/g" "$HOME"/.config/conky/*.conf

## Change paw color for conky build
sed -i -E 's/fill\="[^"]+"//g; s/stroke\="[^"]+"//g' "$HOME/.config/conky/scripts/images/paw-custom.svg"
sed -i "s/<path/<path fill=\"$COLOR_CHOICE\" stroke=\"$COLOR_CHOICE\"/g" "$HOME/.config/conky/scripts/images/paw-custom.svg"
fi
