#!/bin/bash
## Script to toggle apt notifier executor action on/off in tint2

FILE="$HOME/.config/tint2/executors/notifier"
num=$(( $( apt list --upgradable 2>/dev/null | wc -l ) - $( apt-mark showhold | wc -l ) -1 ))
iconpath="$HOME/.config/tint2/executors/icons/update"

if grep -q '#else' "$FILE"; then
sed -i 's/^#if/if/g' "$FILE"
sed -i "0,/#echo/{s/#echo/echo/}" "$FILE"
sed -i 's/^#else/else/g' "$FILE"
notify-send --urgency low -i "$iconpath"/upgrade-green.png 'Apt Upgrade Notifier On'
sleep 1 ; notify-send -t 10000 -u low "$num Update(s) Currently Available" -i "$iconpath"/upgrade-green.png
else
sed -i 's/^if/#if/g' "$FILE"
sed -i "0,/echo/{s/echo/#echo/}" "$FILE"
sed -i 's/^else/#else/g' "$FILE"
notify-send --urgency low -i "$iconpath"/upgrade-blue.png 'Apt Upgrade Notifier Off'
fi
killall -SIGUSR1 tint2
