#!/bin/bash
# tint2 apt notifier color options.
# Made be sleekmason for Lilidog 17 Mar 2023

FILE="$HOME/.config/tint2/scripts/tint2-apt-update-check"
noti=$(yad --width 330 --borders=8 --entry --title "Notifier Icon Color" --center --window-icon=applications-graphics \
    --image="/usr/share/icons/hicolor/24x24/apps/org.xfce.settings.color.png" \
    --button="gtk-cancel:1" --button="gtk-ok:0" \
    "Green" "Blue" "Magenta" "Yellow" "Orange" "Plain" "Red")

case $noti in
  Green)
     sed -i 's/^upgradecolor=.*/upgradecolor="update-green.png"/g' "$FILE"
;;
  Blue)
     sed -i 's/^upgradecolor=.*/upgradecolor="update-blue.png"/g' "$FILE"
;;
  Magenta)
     sed -i 's/^upgradecolor=.*/upgradecolor="update-magenta.png"/g' "$FILE"
;;
  Yellow)
     sed -i 's/^upgradecolor=.*/upgradecolor="update-yellow.png"/g' "$FILE"
;;
  Orange)
     sed -i 's/^upgradecolor=.*/upgradecolor="update-orange.png"/g' "$FILE"
;;
  Plain)
     sed -i 's/^upgradecolor=.*/upgradecolor="update-plain.png"/g' "$FILE"
;;
   Red)
     sed -i 's/^upgradecolor=.*/upgradecolor="update-red.png"/g' "$FILE"
;;
        *) exit 1 ;;
    esac
